/*
 * generated by Xtext 2.34.0
 */
package fr.istic.ui;

import com.google.inject.Injector;
import fr.istic.ui.internal.IsticActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RobotExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(IsticActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		IsticActivator activator = IsticActivator.getInstance();
		return activator != null ? activator.getInjector(IsticActivator.FR_ISTIC_ROBOT) : null;
	}

}
