/*
 * generated by Xtext 2.34.0
 */
package fr.istic.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.istic.RobotRuntimeModule;
import fr.istic.RobotStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class RobotIdeSetup extends RobotStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new RobotRuntimeModule(), new RobotIdeModule()));
	}
	
}
