/*
 * generated by Xtext 2.34.0
 */
package fr.istic.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRobotScopeProvider extends DelegatingScopeProvider {
}
