/*
 * generated by Xtext 2.34.0
 */
package fr.istic.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class RobotUiModule extends AbstractRobotUiModule {

	public RobotUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
