/*
 * generated by Xtext 2.34.0
 */
package fr.istic;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class RobotStandaloneSetup extends RobotStandaloneSetupGenerated {

	public static void doSetup() {
		new RobotStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
